### ISSUE TITLE
error at start Cannot find module 'svelte/internal' 

### ISSUE THREAD

**Issue by ninyawee** [ntsd/astro-svelte-tailwind#1] opened 2023-09-08 08:58 UTC
![image](https://github.com/ntsd/astro-svelte-tailwind/assets/8089231/8f2ffbab-b6c8-49b8-ac75-82af385a31e8)

```
pnpm create astro@latest -- --template ntsd/astro-svelte-tailwind
pnpm i
pnpm dev
```

```
{
  "name": "webapp",
  "description": "Astro Starter Template with Svelte, Tailwind, DaisyUI, and Service Worker",
  "type": "module",
  "version": "0.0.1",
  "author": "Jirawat Boonkumnerd <contact@ntsd.dev> (https://ntsd.dev)",
  "scripts": {
    "dev": "astro dev",
    "start": "astro dev",
    "build": "astro build",
    "preview": "astro preview",
    "astro": "astro"
  },
  "devDependencies": {
    "@astrojs/svelte": "^4.0.0",
    "@astrojs/tailwind": "^5.0.0",
    "@tailwindcss/typography": "^0.5.9",
    "astro": "^3.0.3",
    "astrojs-service-worker": "^1.1.0",
    "autoprefixer": "^10.4.14",
    "daisyui": "^3.5.1",
    "nanostores": "^0.9.3",
    "postcss": "^8.4.24",
    "tailwindcss": "^3.3.2"
  }
}
```

**Comment by ninyawee** [comment] 2023-09-08 09:07
fix by 
```
pnpm astro add svelte
```
cannot run it will fails to find astro binary

must follow by
```
pnpm i
```
```
 WARN  Issues with peer dependencies found
.
└─┬ @astrojs/svelte 4.0.1
  └── ✕ unmet peer astro@^3.0.9: found 3.0.3
````
```
pnpm upgrade 
```

**Comment by ntsd** [comment] 2023-09-08 15:16
The problem is because of pnpm is not installed the `peerDependencies`

you can check here that @astrojs/svelte include svelte

https://github.com/withastro/astro/blob/0a2567c288bc2a3ccc92afd643944c9a4e6d604b/packages/integrations/svelte/package.json#L52

**Comment by ntsd** [comment] 2023-09-08 15:20
Fixed by this https://github.com/ntsd/astro-svelte-tailwind/commit/3614338081810cdd673054ee18cf0a341c9b391f

**Closed as completed by ntsd** 2023-09-08 15:20 UTC
